services:
  - type: web
    name: controle-estoque
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: stock-db
          property: connectionString

databases:
  - name: stock-db
    plan: free
    databaseName: stock
    user: stock_user
